/*
 * build-tool.js — fold the standalone tool into one file.
 *
 *   npm run build:tool          write index.html
 *   node scripts/build-tool.js --check   fail if it is out of date
 *
 * The tool is meant to be a single HTML file you can copy onto a memory stick
 * and open by double-clicking, but its engine is src/ — the same modules the
 * shop's server renders print files with. Copying them into an HTML file by
 * hand would fork that engine on the first bug fix, so the file is generated
 * instead: tool/tool.html is the template, every <script data-inline> and
 * <link data-inline> in it is replaced by the contents of the file it names,
 * and the result is committed the way build-presets.js commits its thumbnails.
 *
 * --check is run by npm test, so an edit to src/ that never reached the built
 * file is a failing test rather than a stale download.
 */
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.join(__dirname, '..');
var TEMPLATE = path.join(ROOT, 'tool', 'tool.html');
var OUT = path.join(ROOT, 'index.html');

var BANNER = [
  '<!--',
  '  Generated by scripts/build-tool.js — do not edit.',
  '',
  '  Sources: tool/tool.html, tool/tool.css, tool/tool-*.js, src/*.js and the',
  '  vendored Leaflet. Run `npm run build:tool` after changing any of them.',
  '',
  '  This file is self-contained: no scripts, styles or images are loaded from',
  '  anywhere. It talks to the network only when you use it — elevation tiles',
  '  from the AWS Terrain Tiles public dataset, place search from OpenStreetMap',
  '  Nominatim, basemap tiles for the picker.',
  '-->'
].join('\n');

/* Leaflet's stylesheet asks for three images by relative path. Inlined as data
 * URIs they follow the file anywhere; left alone they would be three broken
 * requests, and the zoom control would lose its icons. */
function inlineCssImages(css, from) {
  return css.replace(/url\((['"]?)images\/([^)'"]+)\1\)/g, function (whole, quote, name) {
    var file = path.join(path.dirname(from), 'images', name);
    if (!fs.existsSync(file)) return whole;
    return 'url(data:image/png;base64,' + fs.readFileSync(file).toString('base64') + ')';
  });
}

/*
 * Nothing here escapes the inlined text, and nothing needs to: these are this
 * repository's own files, and the one sequence that would end a script block
 * early ("</script>") appears in none of them. It is checked rather than
 * assumed, because a future edit that added one would otherwise produce a file
 * that is broken in a way no test would name.
 */
function guard(source, contents, closer) {
  if (contents.toLowerCase().indexOf(closer) !== -1) {
    throw new Error(source + ' contains "' + closer + '", which would end the block early. ' +
      'Split the string, or teach build-tool.js to escape it.');
  }
}

function build() {
  var template = fs.readFileSync(TEMPLATE, 'utf8');

  var html = template.replace(
    /[ \t]*<(script|link)\b[^>]*\bdata-inline="([^"]+)"[^>]*>(?:<\/script>)?/g,
    function (whole, tag, source) {
      var file = path.join(ROOT, source);
      var contents = fs.readFileSync(file, 'utf8').replace(/\s+$/, '');

      if (tag === 'link') {
        contents = inlineCssImages(contents, file);
        guard(source, contents, '</style');
        return '<style>\n/* ' + source + ' */\n' + contents + '\n</style>';
      }

      guard(source, contents, '</script');
      return '<script>\n/* ' + source + ' */\n' + contents + '\n</script>';
    }
  );

  if (/<(script|link)\b[^>]*\bdata-inline/.test(html)) {
    throw new Error('A tag in tool/tool.html carries data-inline but was not inlined — ' +
      'check its quoting.');
  }

  // Leaflet is MIT and vendored; the licence travels with the code it covers.
  var licence = fs.readFileSync(path.join(ROOT, 'vendor', 'LEAFLET-LICENSE.txt'), 'utf8').trim();
  html = html.replace('<head>', '<head>\n<!--\n' + licence + '\n-->');

  return html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER) + '\n';
}

function main() {
  var html = build();
  var check = process.argv.indexOf('--check') !== -1;
  var current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;

  if (check) {
    if (current === html) {
      console.log('index.html is up to date (' + (html.length / 1024).toFixed(0) + ' KB).');
      return;
    }
    console.error(
      current === null
        ? 'index.html is missing. Run: npm run build:tool'
        : 'index.html is out of date — a source under tool/, src/ or vendor/ has ' +
          'changed since it was built. Run: npm run build:tool'
    );
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, html);
  console.log('index.html — ' + (html.length / 1024).toFixed(0) + ' KB' +
    (current === html ? ' (unchanged)' : ''));
}

if (require.main === module) main();

module.exports = { build: build, OUT: OUT };
