/*
 * build-tool.js — fold the standalone tool into one file.
 *
 *   npm run build:tool          write index.html
 *   node scripts/build-tool.js --check   fail if it is out of date
 *
 * The tool is meant to be a single HTML file you can copy onto a memory stick
 * and open by double-clicking, but its engine is src/ — the same modules the
 * shop's server renders print files with. Copying them into an HTML file by
 * hand would fork that engine on the first bug fix, so the file is generated
 * instead: tool/tool.html is the template, every <script data-inline> and
 * <link data-inline> in it is replaced by the contents of the file it names,
 * and the result is committed the way build-presets.js commits its thumbnails.
 *
 * --check is run by npm test, so an edit to src/ that never reached the built
 * file is a failing test rather than a stale download.
 */
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.join(__dirname, '..');
var TEMPLATE = path.join(ROOT, 'tool', 'tool.html');
var OUT = path.join(ROOT, 'index.html');

var BANNER = [
  '<!--',
  '  Generated by scripts/build-tool.js — do not edit.',
  '',
  '  Sources: tool/tool.html, tool/tool.css, tool/tool-*.js, src/*.js and the',
  '  vendored Leaflet and Source Code Pro. Run `npm run build:tool` after',
  '  changing any of them.',
  '',
  '  This file is self-contained: no scripts, styles, fonts or images are',
  '  loaded from anywhere. It talks to the network only when you use it —',
  '  elevation tiles from the AWS Terrain Tiles public dataset, place search',
  '  from OpenStreetMap Nominatim, basemap tiles for the picker.',
  '-->'
].join('\n');

var MIME = {
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2'
};

/*
 * Stylesheets ask for files by relative path: Leaflet's three control icons,
 * and the Source Code Pro the contours can be lettered in. Inlined as data URIs
 * they follow the built file anywhere; left alone they would be broken requests
 * — and a missing font is worse than a missing icon, because the canvas would
 * silently letter itself in a fallback face with different metrics.
 *
 * Absolute and protocol-relative URLs are left alone: those are somebody
 * deliberately pointing off the file, not an asset to gather up.
 */
function inlineCssAssets(css, from) {
  return css.replace(/url\((['"]?)([^)'"]+)\1\)/g, function (whole, quote, ref) {
    if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|data:|#)/i.test(ref)) return whole;

    var file = path.join(path.dirname(from), ref.split(/[?#]/)[0]);
    var mime = MIME[path.extname(file).toLowerCase()];
    if (!mime || !fs.existsSync(file)) return whole;

    return 'url(data:' + mime + ';base64,' + fs.readFileSync(file).toString('base64') + ')';
  });
}

/* Every licence in vendor/, so adding a vendored thing does not mean
 * remembering to add its notice here as well. */
function licences() {
  return fs.readdirSync(path.join(ROOT, 'vendor'))
    .filter(function (name) { return /LICENSE.*\.txt$/i.test(name); })
    .sort()
    .map(function (name) {
      return fs.readFileSync(path.join(ROOT, 'vendor', name), 'utf8').trim();
    })
    .join('\n\n' + new Array(60).join('=') + '\n\n');
}

/*
 * Nothing here escapes the inlined text, and nothing needs to: these are this
 * repository's own files, and the one sequence that would end a script block
 * early ("</script>") appears in none of them. It is checked rather than
 * assumed, because a future edit that added one would otherwise produce a file
 * that is broken in a way no test would name.
 */
function guard(source, contents, closer) {
  if (contents.toLowerCase().indexOf(closer) !== -1) {
    throw new Error(source + ' contains "' + closer + '", which would end the block early. ' +
      'Split the string, or teach build-tool.js to escape it.');
  }
}

function build() {
  var template = fs.readFileSync(TEMPLATE, 'utf8');

  var html = template.replace(
    /[ \t]*<(script|link)\b[^>]*\bdata-inline="([^"]+)"[^>]*>(?:<\/script>)?/g,
    function (whole, tag, source) {
      var file = path.join(ROOT, source);
      var contents = fs.readFileSync(file, 'utf8').replace(/\s+$/, '');

      if (tag === 'link') {
        contents = inlineCssAssets(contents, file);
        guard(source, contents, '</style');
        return '<style>\n/* ' + source + ' */\n' + contents + '\n</style>';
      }

      guard(source, contents, '</script');
      return '<script>\n/* ' + source + ' */\n' + contents + '\n</script>';
    }
  );

  if (/<(script|link)\b[^>]*\bdata-inline/.test(html)) {
    throw new Error('A tag in tool/tool.html carries data-inline but was not inlined — ' +
      'check its quoting.');
  }

  // Leaflet is MIT, Source Code Pro is under the SIL OFL, and both are
  // vendored; the licences travel with what they cover.
  var licence = licences();
  guard('the vendor licences', licence, '-->');
  html = html.replace('<head>', '<head>\n<!--\n' + licence + '\n-->');

  return html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER) + '\n';
}

function main() {
  var html = build();
  var check = process.argv.indexOf('--check') !== -1;
  var current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;

  if (check) {
    if (current === html) {
      console.log('index.html is up to date (' + (html.length / 1024).toFixed(0) + ' KB).');
      return;
    }
    console.error(
      current === null
        ? 'index.html is missing. Run: npm run build:tool'
        : 'index.html is out of date — a source under tool/, src/ or vendor/ has ' +
          'changed since it was built. Run: npm run build:tool'
    );
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, html);
  console.log('index.html — ' + (html.length / 1024).toFixed(0) + ' KB' +
    (current === html ? ' (unchanged)' : ''));
}

if (require.main === module) main();

module.exports = { build: build, OUT: OUT };
